
version: '3'

services:

  jupyter_notebook:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 8220:8220
    restart: always
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8220", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
